DECLARE 
RADIUS NUMBER;
X NUMBER;
P NUMBER;
BEGIN
CREATE PACKAGE CIRCLE AS
PROCEDURE FIND_AREA(RADIUS IN NUMBER)
RETURN NUMBER IS
Z NUMBER;
BEGIN
Z:=RADIUS*3.14*3.14;
RETURN z;
END;
PROCEDURE FIND_CIRCUMFERENCE(RADIUS IN NUMBER)
RETURN NUMBER IS
Y NUMBER;
BEGIN
Y:=2*3.14*RADIUS;
RETURN Y;
END;
END CIRCLE;
BEGIN
RADIUS:=5;
X:=FIND_AREA(RADIUS);
dbms_output.put_line(' Area: ' || X);
P:=FIND_CIRCUMFERENCE(RADIUS);
dbms_output.put_line('Circumference of circle is: ' || P);
END: